// dashboard-exercisesName.data.ts
export const exercises_name_by_body_part: string[][] = [
  [
    "Deadlift",
    "Hex Bar Deadlift",
    "Power Clean",
    "Romanian Deadlift",
    "Sumo Deadlift",
    "Clean and Jerk",
    "Snatch",
    "Clean",
    "Clean and Press",
    "Rack Pull",
    "Dumbbell Romanian Deadlift",
    "Hang Clean",
    "Stiff Leg Deadlift",
    "Muscle Ups",
    "Power Snatch",
    "Thruster",
    "Push Jerk",
    "Dumbbell Deadlift",
    "Deficit Deadlift",
    "Burpees",
    "Single Leg Romanian Deadlift",
    "Hang Power Clean",
    "Split Jerk",
    "Dumbbell Snatch",
    "Snatch Deadlift",
    "Clean High Pull",
    "Clean Pull",
    "Pause Deadlift",
    "Single Leg Deadlift",
    "Muscle Snatch",
    "Jefferson Deadlift",
    "Snatch Pull",
    "Wall Ball",
    "Zercher Deadlift",
    "Single Leg Dumbbell Deadlift",
    "Dumbbell Clean and Press",
    "Ring Muscle Ups",
    "Hang Snatch",
    "Dumbbell Thruster",
    "Dumbbell High Pull",
    "Behind The Back Deadlift",
    "Dumbbell Hang Clean",
    "Clap Pull Up",
    "Squat Thrust"
  ],
  [
    "Pull Ups",
    "Bent Over Row",
    "Lat Pulldown",
    "Chin Ups",
    "Dumbbell Row",
    "Seated Cable Row",
    "Barbell Shrug",
    "T Bar Row",
    "Dumbbell Shrug",
    "Pendlay Row",
    "Machine Row",
    "Dumbbell Pullover",
    "Dumbbell Reverse Fly",
    "Chest Supported Dumbbell Row",
    "Close Grip Lat Pulldown",
    "Machine Reverse Fly",
    "Reverse Grip Lat Pulldown",
    "Neutral Grip Pull Ups",
    "Straight Arm Pulldown",
    "Back Extension",
    "Bent Over Dumbbell Row",
    "Yates Row",
    "Cable Reverse Fly",
    "Machine Back Extension",
    "Bench Pull",
    "Barbell Pullover",
    "One Arm Pull Ups",
    "Inverted Row",
    "Renegade Row",
    "Dumbbell Bench Pull",
    "One Arm Lat Pulldown",
    "One Arm Seated Cable Row",
    "Cable Upright Row",
    "Machine Shrug",
    "Hex Bar Shrug",
    "Smith Machine Shrug",
    "Dumbbell Incline Y Raise",
    "Cable Shrug",
    "Barbell Power Shrug",
    "Bent Arm Barbell Pullover",
    "Meadows Row",
    "Behind The Back Barbell Shrug",
    "Reverse Hyperextension"
  ],
  [
    "Dumbbell Curl",
    "Barbell Curl",
    "Hammer Curl",
    "EZ Bar Curl",
    "Preacher Curl",
    "Cable Bicep Curl",
    "Incline Dumbbell Curl",
    "Dumbbell Concentration Curl",
    "Machine Bicep Curl",
    "Strict Curl",
    "One Arm Cable Bicep Curl",
    "One Arm Dumbbell Preacher Curl",
    "Incline Hammer Curl",
    "Spider Curl",
    "Seated Dumbbell Curl",
    "Zottman Curl",
    "Cheat Curl",
    "Cable Hammer Curl",
    "One Arm Pulldown",
    "Overhead Cable Curl",
    "Incline Cable Curl",
    "Lying Cable Curl"
  ],
  [
    "Bench Press",
    "Dumbbell Bench Press",
    "Push Ups",
    "Incline Dumbbell Bench Press",
    "Incline Bench Press",
    "Chest Press",
    "Close Grip Bench Press",
    "Machine Chest Fly",
    "Dumbbell Fly",
    "Decline Bench Press",
    "Smith Machine Bench Press",
    "Cable Fly",
    "Floor Press",
    "Incline Dumbbell Fly",
    "Dumbbell Floor Press",
    "Paused Bench Press",
    "Decline Dumbbell Bench Press",
    "One Arm Push Ups",
    "Reverse Grip Bench Press",
    "Diamond Push Ups",
    "Close Grip Dumbbell Bench Press",
    "Bench Pin Press",
    "Wide Grip Bench Press",
    "Decline Push Up",
    "Close Grip Incline Bench Press",
    "Incline Push Up",
    "Close Grip Push Up",
    "Archer Push Ups",
    "Spoto Press",
    "Decline Dumbbell Fly"
  ],
  [
    "Sit Ups",
    "Cable Crunch",
    "Machine Seated Crunch",
    "Crunches",
    "Dumbbell Side Bend",
    "Cable Woodchopper",
    "Hanging Leg Raise",
    "Russian Twist",
    "Lying Leg Raise",
    "Decline Sit Up",
    "Hanging Knee Raise",
    "Ab Wheel Rollout",
    "Toes To Bar",
    "Decline Crunch",
    "Jumping Jack",
    "Bicycle Crunch",
    "Reverse Crunches",
    "Mountain Climbers",
    "Flutter Kicks",
    "High Pulley Crunch",
    "Standing Cable Crunch",
    "Superman",
    "Side Crunch",
    "Roman Chair Side Bend",
    "Scissor Kicks"
  ],
  [
    "Wrist Curl",
    "Reverse Barbell Curl",
    "Reverse Wrist Curl",
    "Dumbbell Wrist Curl",
    "Dumbbell Reverse Wrist Curl",
    "Dumbbell Reverse Curl"
  ],
  [
    "Squat",
    "Sled Leg Press",
    "Front Squat",
    "Hip Thrust",
    "Leg Extension",
    "Horizontal Leg Press",
    "Hack Squat",
    "Seated Leg Curl",
    "Dumbbell Bulgarian Split Squat",
    "Goblet Squat",
    "Lying Leg Curl",
    "Machine Calf Raise",
    "Dumbbell Lunge",
    "Bodyweight Squat",
    "Box Squat",
    "Bulgarian Split Squat",
    "Vertical Leg Press",
    "Smith Machine Squat",
    "Seated Calf Raise",
    "Hip Abduction",
    "Zercher Squat",
    "Good Morning",
    "Barbell Lunge",
    "Hip Adduction",
    "Overhead Squat",
    "Dumbbell Squat",
    "Barbell Calf Raise",
    "Split Squat",
    "Dumbbell Calf Raise",
    "Barbell Reverse Lunge",
    "Cable Pull Through",
    "Standing Leg Curl",
    "Single Leg Press",
    "Landmine Squat",
    "Sled Press Calf Raise",
    "Barbell Glute Bridge",
    "Single Leg Squat",
    "Belt Squat",
    "Safety Bar Squat",
    "Pistol Squat",
    "Pause Squat",
    "Barbell Hack Squat",
    "Sumo Squat",
    "Cable Kickback",
    "Bodyweight Calf Raise",
    "Lunge",
    "Glute Bridge",
    "Pin Squat",
    "Walking Lunge",
    "Dumbbell Front Squat",
    "Dumbbell Split Squat",
    "Reverse Lunge",
    "Squat Jump",
    "Nordic Hamstring Curl",
    "Sissy Squat",
    "Half Squat",
    "Single Leg Seated Calf Raise",
    "Cable Leg Extension",
    "Glute Ham Raise",
    "Side Lunge",
    "Glute Kickback",
    "Donkey Calf Raise",
    "Dumbbell Walking Calf Raise",
    "Side Leg Raise",
    "Floor Hip Abduction",
    "Jefferson Squat",
    "Hip Extension",
    "Floor Hip Extension"
  ],
  [
    "Shoulder Press",
    "Dumbbell Shoulder Press",
    "Dumbbell Lateral Raise",
    "Military Press",
    "Seated Dumbbell Shoulder Press",
    "Seated Shoulder Press",
    "Machine Shoulder Press",
    "Push Press",
    "Upright Row",
    "Dumbbell Front Raise",
    "Cable Lateral Raise",
    "Arnold Press",
    "Face Pull",
    "Neck Curl",
    "Machine Lateral Raise",
    "Dumbbell Upright Row",
    "Handstand Push Ups",
    "Behind The Neck Press",
    "Barbell Front Raise",
    "Log Press",
    "Landmine Press",
    "Neck Extension",
    "Z Press",
    "Viking Press",
    "Shoulder Pin Press",
    "Dumbbell Z Press",
    "One Arm Landmine Press",
    "Pike Push Up",
    "Dumbbell External Rotation",
    "Dumbbell Push Press",
    "Dumbbell Face Pull",
    "Cable External Rotation"
  ],
  [
    "Dips",
    "Tricep Pushdown",
    "Lying Tricep Extension",
    "Tricep Rope Pushdown",
    "Dumbbell Tricep Extension",
    "Tricep Extension",
    "Lying Dumbbell Tricep Extension",
    "Seated Dip Machine",
    "Dumbbell Tricep Kickback",
    "Cable Overhead Tricep Extension",
    "Machine Tricep Extension",
    "Seated Dumbbell Tricep Extension",
    "JM Press",
    "Reverse Grip Tricep Pushdown",
    "Tate Press",
    "Ring Dips",
    "Bench Dips"
  ]
];
